"""
Transcript Export Service.
Generates downloadable files in multiple formats from transcript data.

Formats:
  - TXT: Plain text with optional timestamps/speakers
  - SRT: SubRip subtitle format for video players
  - VTT: WebVTT format for HTML5 video
  - DOCX: Formatted Word document with styles
  - PDF: Print-ready PDF via ReportLab
  - JSON: Machine-readable full transcript data
"""
import io
import json
import logging
import os
from datetime import datetime
from typing import List, Optional, Dict, Any

logger = logging.getLogger(__name__)


def format_timestamp_srt(seconds: float) -> str:
    """Convert seconds to SRT timestamp: HH:MM:SS,mmm"""
    ms = int((seconds % 1) * 1000)
    total_s = int(seconds)
    h = total_s // 3600
    m = (total_s % 3600) // 60
    s = total_s % 60
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def format_timestamp_vtt(seconds: float) -> str:
    """Convert seconds to VTT timestamp: HH:MM:SS.mmm"""
    ms = int((seconds % 1) * 1000)
    total_s = int(seconds)
    h = total_s // 3600
    m = (total_s % 3600) // 60
    s = total_s % 60
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"


def format_timestamp_readable(seconds: float) -> str:
    """Convert seconds to readable [MM:SS] format."""
    total_s = int(seconds)
    m = total_s // 60
    s = total_s % 60
    return f"[{m:02d}:{s:02d}]"


class TranscriptExporter:
    """
    Converts transcript data into various output formats.
    
    Each export method returns bytes ready to write to disk or stream to client.
    """

    def __init__(self, segments: List[Dict], metadata: Dict[str, Any]):
        """
        Args:
            segments: List of segment dicts with keys:
                      text, start_time, end_time, speaker_name, speaker_id, confidence
            metadata: Job/transcript metadata (filename, language, duration, etc.)
        """
        self.segments = segments
        self.metadata = metadata

    def export_txt(
        self,
        include_timestamps: bool = True,
        include_speakers: bool = True,
    ) -> bytes:
        """Plain text transcript."""
        lines = []
        
        # Header
        lines.append(f"TRANSCRIPT: {self.metadata.get('filename', 'Unknown')}")
        lines.append(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        if self.metadata.get("duration"):
            duration = self.metadata["duration"]
            m, s = divmod(int(duration), 60)
            h, m = divmod(m, 60)
            lines.append(f"Duration: {h:02d}:{m:02d}:{s:02d}")
        if self.metadata.get("language"):
            lines.append(f"Language: {self.metadata['language'].upper()}")
        lines.append("=" * 60)
        lines.append("")
        
        current_speaker = None
        
        for seg in self.segments:
            speaker = seg.get("speaker_name") or seg.get("speaker_id")
            text = seg.get("text", "").strip()
            
            if not text:
                continue
            
            parts = []
            
            if include_timestamps:
                ts = format_timestamp_readable(seg.get("start_time", 0))
                parts.append(ts)
            
            if include_speakers and speaker:
                if speaker != current_speaker:
                    current_speaker = speaker
                    if lines and lines[-1] != "":
                        lines.append("")  # Blank line between speakers
                parts.append(f"{speaker}:")
            
            parts.append(text)
            lines.append(" ".join(parts))
        
        return "\n".join(lines).encode("utf-8")

    def export_srt(self) -> bytes:
        """SubRip subtitle format (.srt)"""
        lines = []
        counter = 1
        
        for seg in self.segments:
            text = seg.get("text", "").strip()
            if not text:
                continue
            
            start = format_timestamp_srt(seg.get("start_time", 0))
            end = format_timestamp_srt(seg.get("end_time", 0))
            speaker = seg.get("speaker_name") or seg.get("speaker_id", "")
            
            lines.append(str(counter))
            lines.append(f"{start} --> {end}")
            
            if speaker:
                lines.append(f"<font color='#00FFFF'>{speaker}:</font> {text}")
            else:
                lines.append(text)
            
            lines.append("")  # Blank line separator
            counter += 1
        
        return "\n".join(lines).encode("utf-8")

    def export_vtt(self) -> bytes:
        """WebVTT format for HTML5 video players (.vtt)"""
        lines = ["WEBVTT", ""]
        
        # Optional metadata header
        lines.append(f"NOTE Transcript generated by TranscriptAI")
        lines.append(f"NOTE Language: {self.metadata.get('language', 'unknown')}")
        lines.append("")
        
        counter = 1
        for seg in self.segments:
            text = seg.get("text", "").strip()
            if not text:
                continue
            
            start = format_timestamp_vtt(seg.get("start_time", 0))
            end = format_timestamp_vtt(seg.get("end_time", 0))
            speaker = seg.get("speaker_name") or seg.get("speaker_id", "")
            
            lines.append(f"cue-{counter}")
            lines.append(f"{start} --> {end}")
            
            if speaker:
                lines.append(f"<v {speaker}>{text}")
            else:
                lines.append(text)
            
            lines.append("")
            counter += 1
        
        return "\n".join(lines).encode("utf-8")

    def export_json(self) -> bytes:
        """Machine-readable JSON with full transcript data."""
        output = {
            "metadata": {
                "filename": self.metadata.get("filename"),
                "language": self.metadata.get("language"),
                "duration": self.metadata.get("duration"),
                "speaker_count": self.metadata.get("speaker_count"),
                "word_count": self.metadata.get("word_count"),
                "generated_at": datetime.utcnow().isoformat(),
                "generator": "TranscriptAI v1.0",
            },
            "summary": self.metadata.get("summary"),
            "keywords": self.metadata.get("keywords", []),
            "sentiment": self.metadata.get("sentiment"),
            "segments": [
                {
                    "index": i,
                    "start": seg.get("start_time"),
                    "end": seg.get("end_time"),
                    "text": seg.get("text", "").strip(),
                    "speaker": seg.get("speaker_name") or seg.get("speaker_id"),
                    "confidence": seg.get("confidence"),
                    "words": seg.get("words", []),
                }
                for i, seg in enumerate(self.segments)
                if seg.get("text", "").strip()
            ],
        }
        return json.dumps(output, ensure_ascii=False, indent=2).encode("utf-8")

    def export_docx(
        self,
        include_timestamps: bool = True,
        include_speakers: bool = True,
    ) -> bytes:
        """
        Formatted Word document with professional transcript styling.
        Uses python-docx with custom styles.
        """
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor, Inches
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
        except ImportError:
            logger.error("python-docx not installed. pip install python-docx")
            raise RuntimeError("DOCX export requires python-docx")

        doc = Document()
        
        # Set document margins
        sections = doc.sections
        for section in sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1.2)
            section.right_margin = Inches(1.2)
        
        # Title
        title = doc.add_heading(
            f"Transcript: {self.metadata.get('filename', 'Unknown')}", level=1
        )
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Metadata table
        meta_table = doc.add_table(rows=2, cols=3)
        meta_table.style = "Table Grid"
        
        meta_info = [
            ("Language", self.metadata.get("language", "Unknown").upper()),
            ("Duration", self._format_duration(self.metadata.get("duration", 0))),
            ("Speakers", str(self.metadata.get("speaker_count", "Unknown"))),
            ("Words", str(self.metadata.get("word_count", "Unknown"))),
            ("Generated", datetime.utcnow().strftime("%Y-%m-%d")),
            ("Model", "WhisperX large-v3"),
        ]
        
        cells = [cell for row in meta_table.rows for cell in row.cells]
        for i, (label, value) in enumerate(meta_info[:6]):
            if i < len(cells):
                cells[i].text = f"{label}: {value}"
                for para in cells[i].paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(9)
        
        doc.add_paragraph()
        
        # Summary section
        if self.metadata.get("summary"):
            doc.add_heading("Summary", level=2)
            doc.add_paragraph(self.metadata["summary"])
            doc.add_paragraph()
        
        # Keywords
        if self.metadata.get("keywords"):
            kw_para = doc.add_paragraph()
            run = kw_para.add_run("Keywords: ")
            run.bold = True
            kw_para.add_run(", ".join(self.metadata["keywords"]))
            doc.add_paragraph()
        
        # Transcript
        doc.add_heading("Transcript", level=2)
        
        current_speaker = None
        
        for seg in self.segments:
            text = seg.get("text", "").strip()
            if not text:
                continue
            
            speaker = seg.get("speaker_name") or seg.get("speaker_id")
            
            # Add speaker heading when speaker changes
            if include_speakers and speaker and speaker != current_speaker:
                current_speaker = speaker
                speaker_para = doc.add_paragraph()
                speaker_run = speaker_para.add_run(speaker)
                speaker_run.bold = True
                speaker_run.font.color.rgb = RGBColor(0x34, 0x62, 0xFF)
                speaker_run.font.size = Pt(10)
            
            # Segment paragraph
            para = doc.add_paragraph(style="Normal")
            
            if include_timestamps:
                ts_run = para.add_run(
                    format_timestamp_readable(seg.get("start_time", 0)) + " "
                )
                ts_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
                ts_run.font.size = Pt(9)
            
            text_run = para.add_run(text)
            text_run.font.size = Pt(11)
            para.paragraph_format.space_after = Pt(4)
        
        # Save to bytes
        buffer = io.BytesIO()
        doc.save(buffer)
        return buffer.getvalue()

    def export_pdf(
        self,
        include_timestamps: bool = True,
        include_speakers: bool = True,
    ) -> bytes:
        """
        Professional PDF export using ReportLab.
        """
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import mm
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, 
                Table, TableStyle, HRFlowable
            )
            from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
        except ImportError:
            raise RuntimeError("PDF export requires reportlab: pip install reportlab")
        
        buffer = io.BytesIO()
        
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=30*mm,
            rightMargin=30*mm,
            topMargin=25*mm,
            bottomMargin=25*mm,
        )
        
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            "TranscriptTitle",
            parent=styles["Title"],
            fontSize=18,
            spaceAfter=12,
            textColor=colors.HexColor("#1a1a2e"),
        )
        
        speaker_style = ParagraphStyle(
            "Speaker",
            parent=styles["Normal"],
            fontSize=10,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#3462FF"),
            spaceBefore=12,
            spaceAfter=2,
        )
        
        body_style = ParagraphStyle(
            "TranscriptBody",
            parent=styles["Normal"],
            fontSize=11,
            leading=16,
            spaceAfter=4,
            alignment=TA_JUSTIFY,
        )
        
        ts_style = ParagraphStyle(
            "Timestamp",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.gray,
            fontName="Courier",
        )
        
        story = []
        
        # Title
        filename = self.metadata.get("filename", "Transcript")
        story.append(Paragraph(f"Transcript: {filename}", title_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#3462FF")))
        story.append(Spacer(1, 12))
        
        # Metadata
        meta_data = [
            ["Language", self.metadata.get("language", "Auto-detected").upper(),
             "Duration", self._format_duration(self.metadata.get("duration", 0))],
            ["Speakers", str(self.metadata.get("speaker_count", "—")),
             "Words", str(self.metadata.get("word_count", "—"))],
        ]
        
        meta_table = Table(meta_data, colWidths=[40*mm, 60*mm, 40*mm, 60*mm])
        meta_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#444444")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f8f8f8"), colors.white]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 16))
        
        # Summary
        if self.metadata.get("summary"):
            story.append(Paragraph("<b>Summary</b>", body_style))
            story.append(Paragraph(self.metadata["summary"], body_style))
            story.append(Spacer(1, 12))
        
        # Transcript
        story.append(Paragraph("<b>Transcript</b>", ParagraphStyle(
            "SectionHeader", parent=styles["Normal"],
            fontSize=13, fontName="Helvetica-Bold",
            textColor=colors.HexColor("#1a1a2e"), spaceAfter=8,
        )))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
        story.append(Spacer(1, 8))
        
        current_speaker = None
        
        for seg in self.segments:
            text = seg.get("text", "").strip()
            if not text:
                continue
            
            speaker = seg.get("speaker_name") or seg.get("speaker_id")
            
            if include_speakers and speaker and speaker != current_speaker:
                current_speaker = speaker
                story.append(Paragraph(speaker, speaker_style))
            
            if include_timestamps:
                ts = format_timestamp_readable(seg.get("start_time", 0))
                story.append(Paragraph(ts, ts_style))
            
            story.append(Paragraph(text, body_style))
        
        doc.build(story)
        return buffer.getvalue()

    def _format_duration(self, seconds: float) -> str:
        total_s = int(seconds)
        h, rem = divmod(total_s, 3600)
        m, s = divmod(rem, 60)
        if h > 0:
            return f"{h}h {m:02d}m {s:02d}s"
        return f"{m}m {s:02d}s"
